export const SET_SELECTED_SESSION = "SET_SELECTED_SESSION";
export const SET_SELECTED_SESSION_BY_ID = "SET_SELECTED_SESSION_BY_ID";

export const USER_LOGOUT = "USER_LOGOUT";

export const UPDATE_SESSIONS = "UPDATE_SESSIONS";
