export const SET_SELECTED_SESSION = "SET_SELECTED_SESSION";
export const SET_SELECTED_SESSION_BY_ID = "SET_SELECTED_SESSION_BY_ID";
export const SET_SESSIONS = "SET_SESSIONS";

export const SET_USER_UID = "SET_USER_UID";
export const USER_LOGOUT = "USER_LOGOUT";
